name: filter
channels:
  - bioconda
  - conda-forge
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bcftools=1.19=h8b25389_1
  - bedtools=2.31.1=hf5e1c6e_2
  - blas=1.0=openblas
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2024.11.26=h06a4308_0
  - gsl=2.7=he838d99_0
  - htslib=1.21=h5efdd21_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libcurl=8.8.0=hca28451_1
  - libdeflate=1.21=h4bc722e_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - ncurses=6.5=he02047a_1
  - numpy=1.26.4=py312h2809609_0
  - numpy-base=1.26.4=py312he1a6c75_0
  - openssl=3.4.0=hb9d3cd8_0
  - perl=5.32.1=7_hd590300_perl5
  - pip=24.3.1=pyh8b19718_0
  - python=3.12.1=hab00c5b_1_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.6.0=pyhff2d567_1
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024b=hc8b5060_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xz=5.2.6=h166bdaf_0
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - biopython==1.84
      - pysam==0.22.1
      - edlib==1.3.9.post1
